"""Ajusta tabela "users" adcionando compo focus

Revision ID: 354779cab165
Revises: ce7a17731647
Create Date: 2026-04-22 19:56:04.048774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354779cab165'
down_revision: Union[str, Sequence[str], None] = 'ce7a17731647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('focus', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'focus')
    # ### end Alembic commands ###
