"""Adiciona tabela Pomo

Revision ID: 6189e513ea25
Revises: 94dd7aafffd2
Create Date: 2025-11-29 18:09:12.325553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6189e513ea25'
down_revision: Union[str, Sequence[str], None] = '94dd7aafffd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pomo', sa.Column('session_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('pomo', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pomo', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('pomo', 'session_date')
    # ### end Alembic commands ###
