"""Adiciona o campo "project" a tabela usuario

Revision ID: ce7a17731647
Revises: 4b073a17218a
Create Date: 2026-03-20 21:47:09.308461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce7a17731647'
down_revision: Union[str, Sequence[str], None] = '4b073a17218a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('project', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'project')
    # ### end Alembic commands ###
