"""Atualiza tabela "pomo" criando um foreignKey no campo "user_id"

Revision ID: cea0c6259941
Revises: dc98e58e5b19
Create Date: 2026-05-18 19:04:12.564914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea0c6259941'
down_revision: Union[str, Sequence[str], None] = 'dc98e58e5b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pomo', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pomo', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pomo', type_='foreignkey')
    op.drop_column('pomo', 'user_id')
    # ### end Alembic commands ###
