"""Ajusta tabela "users" removendo linha "projec"

Revision ID: dc98e58e5b19
Revises: 354779cab165
Create Date: 2026-04-22 21:00:11.205770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc98e58e5b19'
down_revision: Union[str, Sequence[str], None] = '354779cab165'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'project')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('project', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
